### ISSUE TITLE
Error in Workflow '/Users/....' : <urlopen error [Errno 64] Host is down> 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [deanishe/alfred-stackoverflow#1]
![screen shot 2015-03-22 at 5 21 00 pm](https://cloud.githubusercontent.com/assets/8083613/6769244/fa703734-d0b8-11e4-8165-8f79681fbd7b.png)

**Comment by AbhimanyuAryan** [comment]
I see there is some error in the python file. I also tried to look at .py file but this doesn't show me complete path where in Library this file is kept

**Comment by deanishe** [comment]
You would need to check the log file or Alfred's debugger to see the full error message.

Even without the full traceback, the error seems fairly clear: [Errno 64] **Host is down**

The StackOverflow site wasn't available when you used the workflow. It was a problem with StackOverflow, not the workflow.

**Comment by Kobold** [comment]
As a note to others coming to this issue from google, `[Errno 64] Host is down` has been caused by Little Snitch for me — try turning it off and see if the problem goes away.
