### ISSUE TITLE
Multiple word queries not working?

### ISSUE THREAD

**Issue by coryfklein** [deanishe/alfred-stackoverflow#3]
Queries that contain multiple words don't seem to work.

For example, if I search for "scala" I get these results:

![image](https://cloud.githubusercontent.com/assets/3503322/13441094/d112706e-dfb2-11e5-8ca1-f906b52fea8e.png)

Clearly the first result has something to do with Groovy, so if I search for "scala groovy" I would expect to see that question, but instead I see this:

![image](https://cloud.githubusercontent.com/assets/3503322/13441101/daebdbfc-dfb2-11e5-8251-2771b2d66534.png)

**Comment by deanishe** [comment]
Thanks! Fixed in [v1.2](https://github.com/deanishe/alfred-stackoverflow/releases/tag/v1.2).
