### ISSUE TITLE
Add if no question not found open in SO search

### ISSUE THREAD

**Issue by muuvmuuv** [deanishe/alfred-stackoverflow#6]
It's pretty nice but seems like it only finds questions where the headline is equal to my search query. StackOverflow tries to find similar questions when searching. If this is not possible add something like "Search for xyz on StackOverflow". So it would at least show more questions there.

**Comment by muuvmuuv** [comment]
Related to #5

**Comment by deanishe** [comment]
v2 now uses the advanced search API.
