### ISSUE TITLE
Is there a way to add support to stack teams?

### ISSUE THREAD

**Issue by DaveEzrakhovich** [deanishe/alfred-stackoverflow#8]
Hi 
I've recently started using stackoverflow teams ("internal" knowledge sharing) 
It's the same stackoverflow api and address except one thing it's restricted to authenticated users, 
I couldn't figure out how can I add it to the siteids but is there a way? Can I assist in some way?

**Comment by deanishe** [comment]
You'd have to hardcode your team sites, as the API won't provide them.

The API requires OAuth authentication, which I wouldn't be thrilled about adding to the workflow in any case, but the way they've implemented it means I'd have to use an embedded browser control. 

That's way out of scope, I'm afraid.
